config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create] do
    collection do
      get :signout
    end
  end

  resources :boards
  resources :memos

  root 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :memos
  belongs_to :user

  validates_presence_of :user
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  private

  def login_check
    unless session[:user_id]
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) rescue nil
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :login_check

  def index
    @boards = current_user.boards

    render template: 'root/root'
  end

  def create
    name = params.require(:name)
    
    begin
      @board = Board.create!(name: name, user: current_user)
    rescue => ex
      Rails.logger.warn ex
      render text: "なにかがおかしいよ", status: 400 and return
    end

    render json: @board and return
  end

  # GET /boards/:id
  def show
    id = params.require(:id)

    @board = Board.find(id)
    @memos = @board.memos
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # SHow login view
  def new
  end

  # Login
  def create
    id_name = params[:id_name]
    pass    = params[:password]

    e = -> (msg) {
      flash.alert = msg
      redirect_to action: :new
    }
    if id_name.blank?
      e.("IDを入力してください。");return
    end

    if pass.blank?
      e.("passwordを入力してください。");return
    end

    user = User.find_by(id_name: id_name)

    unless user && user.authenticate(pass)
      e.("ユーザー認証に失敗しました。");return
    end

    session[:user_id] = user.id
    flash.notice = 'Sign in が完了しました。'
    redirect_to root_path; return
  end

  def signout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag "application", media: "all"
    title Memo
    = csrf_meta_tags


body
  nav.navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar-top-collapse"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#{root_path}" Memo
      .navbar-collapse.collapse#navbar-top-collapse
        ul.nav.navbar-nav
          - if current_user
            li
              a href="#{signout_sessions_path}" Sign out
          - else
            li
              a href="#{new_session_path}" Sign in



  .container
    - if flash.alert
      .alert.alert-danger.fade.in
        | #{flash.alert}
        button.close type="button" aria-label="Close" data-dismiss="alert"
          span aria-hidden="true" &times;
    - if flash.notice
      .alert.alert-success.fade.in
        | #{flash.notice}
        button.close type="button" aria-label="Close" data-dismiss="alert"
          span aria-hidden="true" &times;


    == yield


  footer.navbar.navbar-default.navbar-fixed-bottom role='contentinfo'
    .container
      p.navbar-text
        | Copyright &copy; 2015&nbsp;
        a href="http://me.pocke.me" target="_blank" pocke&nbsp;
        | Licensed&nbsp;
        a href="http://www.opensource.org/licenses/mit-license.php" target="_blank" MIT

  javascript:
    var BOARDS = #{{@boards.to_json}}

  = javascript_include_tag "application"

app/views/root/root.html.slim
.row#root

  .col-xs-3
    h4 Boards
    .list-group
      a.list-group-item href="#" v-repeat="boards" v-text="name" v-on="click: show(id)" v-class="active: current.id === id"
      hr
      button.btn.btn-primary.btn-sm v-on="click: AddBoard()" New Board

  .col-xs-9 v-if="current"
    h4
      span v-text="current.name"
      | &nbsp;
      small v-text="current.description"

    div v-repeat="current.memos" v-text="text"